Fix wrong option (and I believe a typo) for nixos-rebuild
All other `nixos-rebuild` command on this page use (I believe) the correct `--option` except this one.

passing `--options` to `nix` here on my system will result in

> error: unrecognised flag '--options'

I have only macOS at the moment, so this is just a guess and you should test it before accepting this change.